#!/usr/bin/env python3
"""
Project setup script for fotbollsplan-bevattning.

This script automates the initial setup of the project by:
1. Creating a .env file with API_KEY, MODBUS_HOST, MODBUS_PORT, and MODBUS_UNIT
2. Installing Python dependencies from requirements.txt files
3. Optionally installing and configuring Tailscale for SSH access
4. Configuring firewall rules for Tailscale (if ufw is available)
"""

import os
import sys
import subprocess
import re
from pathlib import Path
from typing import Tuple, Optional


# Constants
DEFAULT_API_KEY = 'byt-mig'
DEFAULT_MODBUS_HOST = '127.0.0.1'
DEFAULT_MODBUS_PORT = '502'
DEFAULT_MODBUS_UNIT = '1'
DEFAULT_SMTP_HOST = 'smtp.gmail.com'
DEFAULT_SMTP_PORT = '587'
DEFAULT_SMTP_TIMEOUT = '10'
DEFAULT_HEALTHCHECK_TIMEOUT = '5'
DEFAULT_HEALTHCHECK_RETRIES = '3'


def print_header(text: str) -> None:
    """Print a formatted header."""
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60 + "\n")


def print_success(text: str) -> None:
    """Print a success message."""
    print(f"✓ {text}")


def print_error(text: str) -> None:
    """Print an error message."""
    print(f"✗ {text}", file=sys.stderr)


def print_info(text: str) -> None:
    """Print an informational message."""
    print(f"ℹ {text}")


def validate_ipv4(ip: str) -> bool:
    """Validate IPv4 address format."""
    pattern = r'^(\d{1,3}\.){3}\d{1,3}$'
    if not re.match(pattern, ip):
        return False
    
    # Check that each octet is 0-255
    octets = ip.split('.')
    for octet in octets:
        try:
            if not 0 <= int(octet) <= 255:
                return False
        except ValueError:
            return False
    
    return True


def validate_port(port_str: str) -> Tuple[bool, int]:
    """Validate port number (1-65535)."""
    try:
        port = int(port_str)
        if 1 <= port <= 65535:
            return True, port
        return False, 0
    except ValueError:
        return False, 0


def validate_unit_id(unit_str: str) -> Tuple[bool, int]:
    """Validate Modbus unit ID (1-255)."""
    try:
        unit = int(unit_str)
        if 1 <= unit <= 255:
            return True, unit
        return False, 0
    except ValueError:
        return False, 0


def get_input(prompt: str, default: str = None, validator=None) -> str:
    """Get user input with optional default and validation."""
    while True:
        if default:
            user_input = input(f"{prompt} [{default}]: ").strip()
            if not user_input:
                user_input = default
        else:
            user_input = input(f"{prompt}: ").strip()
        
        if not user_input:
            print_error("Input cannot be empty. Please try again.")
            continue
        
        if validator:
            result = validator(user_input)
            # Handle both bool and tuple returns
            if isinstance(result, tuple):
                valid, _ = result
                if valid:
                    return user_input
            elif result:
                return user_input
            
            print_error("Invalid input. Please try again.")
            continue
        
        return user_input


def get_yes_no(prompt: str, default: bool = False) -> bool:
    """Get yes/no input from user."""
    default_str = "Y/n" if default else "y/N"
    while True:
        response = input(f"{prompt} [{default_str}]: ").strip().lower()
        if not response:
            return default
        if response in ['y', 'yes']:
            return True
        if response in ['n', 'no']:
            return False
        print_error("Please answer 'y' or 'n'.")


def load_existing_env(env_file: Path) -> dict:
    """
    Load existing environment variables from .env file.
    
    NOTE: This function is duplicated in install.py. Consider extracting
    to a shared utility module in future refactoring.
    """
    env_vars = {}
    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    if '=' in line:
                        key, value = line.split('=', 1)
                        env_vars[key.strip()] = value.strip()
    return env_vars


def save_env_file(env_file: Path, env_vars: dict) -> None:
    """
    Save environment variables to .env file.
    
    NOTE: This function is duplicated in install.py with slight differences.
    Consider extracting to a shared utility module in future refactoring.
    """
    with open(env_file, 'w') as f:
        f.write("# Fotbollsplan-bevattning Environment Configuration\n")
        f.write("# Generated by setup.py\n\n")
        
        # Group related variables
        f.write("# API Configuration\n")
        for key in ['API_KEY', 'API_URL', 'MODBUS_HOST', 'MODBUS_PORT', 'MODBUS_UNIT']:
            if key in env_vars:
                f.write(f"{key}={env_vars[key]}\n")
        
        f.write("\n# Dash Process View Configuration\n")
        for key in ['DASH_HOST', 'DASH_PORT']:
            if key in env_vars:
                f.write(f"{key}={env_vars[key]}\n")
        
        f.write("\n# Weather Data Location (for Open-Meteo API)\n")
        for key in ['LATITUDE', 'LONGITUDE']:
            if key in env_vars:
                f.write(f"{key}={env_vars[key]}\n")
        
        f.write("\n# SMTP Configuration (for healthcheck email notifications)\n")
        f.write("# Use install.py to configure these interactively\n")
        smtp_keys = ['SMTP_HOST', 'SMTP_PORT', 'SMTP_USER', 'SMTP_PASS', 
                     'SMTP_FROM', 'SMTP_TO', 'SMTP_TIMEOUT']
        for key in smtp_keys:
            if key in env_vars:
                f.write(f"{key}={env_vars[key]}\n")
        
        f.write("\n# Healthcheck Configuration\n")
        healthcheck_keys = ['HEALTHCHECK_TIMEOUT', 'HEALTHCHECK_RETRIES']
        for key in healthcheck_keys:
            if key in env_vars:
                f.write(f"{key}={env_vars[key]}\n")
        
        # Add any other remaining variables
        written_keys = set(['API_KEY', 'API_URL', 'MODBUS_HOST', 'MODBUS_PORT', 'MODBUS_UNIT',
                           'DASH_HOST', 'DASH_PORT', 'LATITUDE', 'LONGITUDE'] + 
                          smtp_keys + healthcheck_keys)
        other_vars = {k: v for k, v in env_vars.items() if k not in written_keys}
        if other_vars:
            f.write("\n# Other Configuration\n")
            for key, value in other_vars.items():
                f.write(f"{key}={value}\n")


def check_pip() -> bool:
    """Check if pip is available and install if necessary."""
    print_info("Checking for pip...")
    
    try:
        result = subprocess.run(
            [sys.executable, '-m', 'pip', '--version'],
            capture_output=True,
            text=True,
            timeout=10
        )
        if result.returncode == 0:
            print_success("pip is available")
            return True
    except Exception:
        pass
    
    print_info("pip not found. Attempting to install pip...")
    
    try:
        # Try to install pip using ensurepip
        result = subprocess.run(
            [sys.executable, '-m', 'ensurepip', '--default-pip'],
            capture_output=True,
            text=True,
            timeout=60
        )
        
        if result.returncode == 0:
            print_success("pip installed successfully")
            return True
        else:
            print_error(f"Failed to install pip: {result.stderr}")
            return False
    
    except Exception as e:
        print_error(f"Failed to install pip: {e}")
        return False


def install_requirements(requirements_file: Path) -> bool:
    """Install Python dependencies from a requirements file."""
    if not requirements_file.exists():
        print_info(f"Requirements file not found: {requirements_file}")
        return True  # Not an error if file doesn't exist
    
    print_info(f"Installing dependencies from {requirements_file.name}...")
    
    try:
        result = subprocess.run(
            [sys.executable, '-m', 'pip', 'install', '-r', str(requirements_file)],
            capture_output=True,
            text=True,
            timeout=300  # 5 minutes timeout
        )
        
        if result.returncode == 0:
            print_success(f"Dependencies from {requirements_file.name} installed successfully")
            return True
        else:
            print_error(f"Failed to install dependencies from {requirements_file.name}")
            print_error(result.stderr)
            return False
    
    except subprocess.TimeoutExpired:
        print_error(f"Installation timed out for {requirements_file.name}")
        return False
    except Exception as e:
        print_error(f"Error installing dependencies from {requirements_file.name}: {e}")
        return False


def is_tailscale_installed() -> bool:
    """Check if Tailscale is installed."""
    try:
        result = subprocess.run(
            ['which', 'tailscale'],
            capture_output=True,
            text=True,
            timeout=5
        )
        return result.returncode == 0
    except Exception:
        return False


def install_tailscale() -> bool:
    """
    Install Tailscale using the official installation method.
    
    NOTE: This downloads and executes a script from tailscale.com.
    While this is the official installation method recommended by Tailscale,
    it does execute remote code with sudo privileges. The script is downloaded
    over HTTPS to ensure transport security.
    
    For maximum security, consider manually verifying the script or using
    your distribution's package manager if Tailscale is available there.
    """
    print_info("Installing Tailscale...")
    print_info("This will download and run the official Tailscale install script with sudo")
    
    if not get_yes_no("Do you want to continue?", default=True):
        print_info("Tailscale installation cancelled")
        return False
    
    try:
        # Use the official Tailscale installation method
        # This is recommended by Tailscale: https://tailscale.com/download/linux
        result = subprocess.run(
            ['sh', '-c', 'curl -fsSL https://tailscale.com/install.sh | sudo sh'],
            capture_output=True,
            text=True,
            timeout=120,
            shell=False
        )
        
        if result.returncode == 0:
            print_success("Tailscale installed successfully")
            return True
        else:
            print_error(f"Failed to install Tailscale: {result.stderr}")
            return False
    
    except subprocess.TimeoutExpired:
        print_error("Tailscale installation timed out")
        return False
    except Exception as e:
        print_error(f"Error installing Tailscale: {e}")
        return False


def configure_tailscale() -> bool:
    """Configure Tailscale with SSH enabled."""
    print_info("Configuring Tailscale with SSH...")
    
    try:
        result = subprocess.run(
            ['sudo', 'tailscale', 'up', '--ssh'],
            capture_output=True,
            text=True,
            timeout=60
        )
        
        if result.returncode == 0:
            print_success("Tailscale configured with SSH enabled")
            print_info("Follow the authentication URL in the output above to complete setup")
            if result.stdout:
                print(result.stdout)
            return True
        else:
            print_error(f"Failed to configure Tailscale: {result.stderr}")
            return False
    
    except subprocess.TimeoutExpired:
        print_error("Tailscale configuration timed out")
        return False
    except Exception as e:
        print_error(f"Error configuring Tailscale: {e}")
        return False


def is_ufw_available() -> bool:
    """Check if ufw is available."""
    try:
        result = subprocess.run(
            ['which', 'ufw'],
            capture_output=True,
            text=True,
            timeout=5
        )
        return result.returncode == 0
    except Exception:
        return False


def configure_ufw_for_tailscale() -> bool:
    """Configure ufw firewall for Tailscale."""
    if not is_ufw_available():
        print_info("ufw not found, skipping firewall configuration")
        return True
    
    print_info("Configuring ufw firewall for Tailscale...")
    
    # Tailscale uses UDP port 41641
    rules = [
        ['sudo', 'ufw', 'allow', '41641/udp', 'comment', 'Tailscale'],
    ]
    
    try:
        for rule in rules:
            result = subprocess.run(
                rule,
                capture_output=True,
                text=True,
                timeout=10
            )
            
            if result.returncode != 0:
                print_error(f"Failed to add firewall rule: {' '.join(rule[2:])}")
                print_error(result.stderr)
                return False
        
        print_success("Firewall rules configured for Tailscale")
        print_info("Note: Ensure ufw is enabled with 'sudo ufw enable'")
        return True
    
    except Exception as e:
        print_error(f"Error configuring firewall: {e}")
        return False


def setup_tailscale() -> bool:
    """Setup Tailscale installation and configuration."""
    print_header("Tailscale Installation and Configuration")
    
    if is_tailscale_installed():
        print_success("Tailscale is already installed")
        
        if not get_yes_no("Do you want to reconfigure Tailscale?", default=False):
            return True
        
        if not configure_tailscale():
            return False
    else:
        print_info("Tailscale is not installed")
        
        if not get_yes_no("Do you want to install and configure Tailscale?", default=True):
            print_info("Skipping Tailscale installation")
            return True
        
        if not install_tailscale():
            return False
        
        if not configure_tailscale():
            return False
    
    # Configure firewall if available
    if get_yes_no("Do you want to configure firewall rules for Tailscale?", default=True):
        configure_ufw_for_tailscale()
    
    return True


def main() -> int:
    """Main setup script."""
    print_header("Fotbollsplan-bevattning Project Setup")
    
    print("This script will help you set up the project by:")
    print("  • Creating a .env configuration file")
    print("  • Installing Python dependencies")
    print("  • Optionally installing and configuring Tailscale\n")
    
    # Determine project directory
    script_dir = Path(__file__).parent.resolve()
    env_file = script_dir / "api_.env"
    
    # Step 1: Configure .env file
    print_header("Environment Configuration")
    
    # Check if .env file already exists
    if env_file.exists():
        print_info(f"Found existing configuration file: {env_file}")
        if not get_yes_no("Do you want to update it?", default=True):
            print_info("Keeping existing configuration")
            existing_vars = load_existing_env(env_file)
        else:
            existing_vars = load_existing_env(env_file)
            # Prompt for updates
            print("\nCurrent values will be shown as defaults.")
            print("Press Enter to keep the current value.\n")
            
            # API Key
            default_key = existing_vars.get('API_KEY', DEFAULT_API_KEY)
            api_key = get_input("API Key", default=default_key)
            
            # Modbus Host
            default_host = existing_vars.get('MODBUS_HOST', DEFAULT_MODBUS_HOST)
            modbus_host = get_input("Modbus Host (IP address)", 
                                   default=default_host, validator=validate_ipv4)
            
            # Modbus Port
            default_port = existing_vars.get('MODBUS_PORT', DEFAULT_MODBUS_PORT)
            modbus_port = get_input("Modbus Port", default=default_port, 
                                   validator=validate_port)
            
            # Modbus Unit
            default_unit = existing_vars.get('MODBUS_UNIT', DEFAULT_MODBUS_UNIT)
            modbus_unit = get_input("Modbus Unit ID", default=default_unit,
                                   validator=validate_unit_id)
            
            # Update env vars
            existing_vars['API_KEY'] = api_key
            existing_vars['MODBUS_HOST'] = modbus_host
            existing_vars['MODBUS_PORT'] = modbus_port
            existing_vars['MODBUS_UNIT'] = modbus_unit
    else:
        print_info(f"Will create new configuration file: {env_file}")
        
        # Load from example file if it exists
        example_file = script_dir / "api_.env.example"
        if example_file.exists():
            existing_vars = load_existing_env(example_file)
        else:
            existing_vars = {}
        
        # Prompt for configuration
        api_key = get_input("API Key", default=DEFAULT_API_KEY)
        modbus_host = get_input("Modbus Host (IP address)", 
                               default=DEFAULT_MODBUS_HOST, validator=validate_ipv4)
        modbus_port = get_input("Modbus Port", default=DEFAULT_MODBUS_PORT,
                               validator=validate_port)
        modbus_unit = get_input("Modbus Unit ID", default=DEFAULT_MODBUS_UNIT,
                               validator=validate_unit_id)
        
        # Set env vars
        existing_vars['API_KEY'] = api_key
        existing_vars['MODBUS_HOST'] = modbus_host
        existing_vars['MODBUS_PORT'] = modbus_port
        existing_vars['MODBUS_UNIT'] = modbus_unit
        
        # Set default SMTP values if not present
        if 'SMTP_HOST' not in existing_vars:
            existing_vars['SMTP_HOST'] = DEFAULT_SMTP_HOST
        if 'SMTP_PORT' not in existing_vars:
            existing_vars['SMTP_PORT'] = DEFAULT_SMTP_PORT
        if 'SMTP_TIMEOUT' not in existing_vars:
            existing_vars['SMTP_TIMEOUT'] = DEFAULT_SMTP_TIMEOUT
        if 'HEALTHCHECK_TIMEOUT' not in existing_vars:
            existing_vars['HEALTHCHECK_TIMEOUT'] = DEFAULT_HEALTHCHECK_TIMEOUT
        if 'HEALTHCHECK_RETRIES' not in existing_vars:
            existing_vars['HEALTHCHECK_RETRIES'] = DEFAULT_HEALTHCHECK_RETRIES
        
        # Set default Dash and location values if not present
        if 'DASH_PORT' not in existing_vars:
            existing_vars['DASH_PORT'] = '8050'
        if 'DASH_HOST' not in existing_vars:
            existing_vars['DASH_HOST'] = '0.0.0.0'
        if 'API_URL' not in existing_vars:
            existing_vars['API_URL'] = 'http://127.0.0.1:8000'
        if 'LATITUDE' not in existing_vars:
            existing_vars['LATITUDE'] = '55.6050'  # Malmö
        if 'LONGITUDE' not in existing_vars:
            existing_vars['LONGITUDE'] = '13.0038'  # Malmö
    
    # Ask about Dash Process View configuration
    print_header("Dash Process View Configuration (Valfritt)")
    print("Dash Process View är en grafisk webbapp för realtidsövervakning.")
    print("Den kan köras parallellt med FastAPI på en annan port.\n")
    
    if get_yes_no("Vill du konfigurera Dash Process View?", default=True):
        # Dash configuration
        default_dash_port = existing_vars.get('DASH_PORT', '8050')
        dash_port = get_input("Dash Process View port", default=default_dash_port, 
                             validator=validate_port)
        existing_vars['DASH_PORT'] = dash_port
        
        default_api_url = existing_vars.get('API_URL', 'http://127.0.0.1:8000')
        api_url = get_input("FastAPI URL (för Dash att ansluta till)", 
                           default=default_api_url)
        existing_vars['API_URL'] = api_url
        
        # Location for weather data
        if get_yes_no("Vill du konfigurera plats för väderdata?", default=True):
            print("\nAnge koordinater för väderprognos (Open-Meteo):")
            print("Standard är Malmö (55.6050, 13.0038)")
            
            default_lat = existing_vars.get('LATITUDE', '55.6050')
            latitude = get_input("Latitud (grader)", default=default_lat)
            existing_vars['LATITUDE'] = latitude
            
            default_lon = existing_vars.get('LONGITUDE', '13.0038')
            longitude = get_input("Longitud (grader)", default=default_lon)
            existing_vars['LONGITUDE'] = longitude
            
            print_success(f"Väderdata kommer hämtas för koordinater: {latitude}, {longitude}")
    
    else:
        # Set defaults even if user skips configuration
        if 'DASH_PORT' not in existing_vars:
            existing_vars['DASH_PORT'] = '8050'
        if 'API_URL' not in existing_vars:
            existing_vars['API_URL'] = 'http://127.0.0.1:8000'
        if 'LATITUDE' not in existing_vars:
            existing_vars['LATITUDE'] = '55.6050'
        if 'LONGITUDE' not in existing_vars:
            existing_vars['LONGITUDE'] = '13.0038'
        print_info("Standardvärden sätts för Dash Process View")
    
    # Save configuration
    try:
        save_env_file(env_file, existing_vars)
        print_success(f"Configuration saved to: {env_file}")
    except Exception as e:
        print_error(f"Failed to save configuration: {e}")
        return 1
    
    # Step 2: Install Python dependencies
    print_header("Python Dependencies")
    
    if not check_pip():
        print_error("pip is required but could not be installed")
        print_info("Please install pip manually and run this script again")
        return 1
    
    # Install api_requirements.txt
    api_requirements = script_dir / "api_requirements.txt"
    if not install_requirements(api_requirements):
        print_error("Failed to install API requirements")
        if not get_yes_no("Do you want to continue anyway?", default=False):
            return 1
    
    # Install display_requirements.txt
    display_requirements = script_dir / "display_requirements.txt"
    if not install_requirements(display_requirements):
        print_error("Failed to install display requirements")
        if not get_yes_no("Do you want to continue anyway?", default=False):
            return 1
    
    # Step 3: Tailscale setup (optional)
    if not setup_tailscale():
        print_error("Tailscale setup failed")
        if not get_yes_no("Do you want to continue anyway?", default=True):
            return 1
    
    # Final summary
    print_header("Setup Complete!")
    print("Your project has been set up successfully.\n")
    print("Next steps:")
    print("  1. Review and update api_.env if needed")
    print("  2. Configure SMTP for email notifications: python3 install.py")
    print("  3. Start FastAPI: uvicorn api_main:app --host 0.0.0.0 --port 8000")
    print("  4. Start Dash Process View: python3 dash_app.py")
    print("  5. Access web interfaces:")
    print(f"     - FastAPI UI: http://localhost:8000")
    print(f"     - Dash Process View: http://localhost:{existing_vars.get('DASH_PORT', '8050')}")
    print("  6. See README.md for more information\n")
    
    if is_tailscale_installed():
        print("Tailscale is installed. To check status:")
        print("  sudo tailscale status")
        print("  sudo tailscale ip\n")
    
    print("För produktionsmiljö, överväg att sätta upp systemd services:")
    print("  - systemd_bevattning-api.service (FastAPI)")
    print("  - systemd_dash-process-view.service (Dash Process View)")
    print("  Se README.md för instruktioner.\n")
    
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print_error(f"Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
